import { jsPDF } from "jspdf";

export function getMethodBadgeClass(method) {
  switch (method?.toUpperCase()) {
    case "GET":
      return "bg-emerald-50 text-emerald-700 border-emerald-200 ring-1 ring-emerald-500/20";
    case "POST":
      return "bg-indigo-50 text-indigo-700 border-indigo-200 ring-1 ring-indigo-500/20";
    case "PUT":
      return "bg-amber-50 text-amber-700 border-amber-200 ring-1 ring-amber-500/20";
    case "DELETE":
      return "bg-rose-50 text-rose-700 border-rose-200 ring-1 ring-rose-500/20";
    case "PATCH":
      return "bg-purple-50 text-purple-700 border-purple-200 ring-1 ring-purple-500/20";
    default:
      return "bg-slate-50 text-slate-700 border-slate-200";
  }
}

export function getPriorityBadgeClass(priority) {
  switch (priority?.toLowerCase()) {
    case "high":
      return "bg-rose-50 text-rose-700 border-rose-200";
    case "medium":
      return "bg-amber-50 text-amber-700 border-amber-200";
    case "low":
      return "bg-emerald-50 text-emerald-700 border-emerald-200";
    default:
      return "bg-slate-50 text-slate-700 border-slate-200";
  }
}

export function exportProjectToWord(project) {
  const design = project?.design;
  if (!design) return;

  const content = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${project.title} - Technical System Design Document</title>
  <style>
    body { font-family: Calibri, Arial, sans-serif; line-height: 1.6; color: #1e293b; padding: 30px; }
    h1 { color: #4338ca; border-bottom: 2px solid #4338ca; padding-bottom: 8px; font-size: 24pt; }
    h2 { color: #1e1b4b; border-bottom: 1px solid #cbd5e1; padding-bottom: 4px; margin-top: 24pt; font-size: 16pt; }
    h3 { color: #3730a3; font-size: 13pt; margin-top: 14pt; }
    p { margin: 8pt 0; }
    table { width: 100%; border-collapse: collapse; margin: 12pt 0; }
    th { background-color: #f1f5f9; text-align: left; padding: 8px; border: 1px solid #cbd5e1; font-weight: bold; }
    td { padding: 8px; border: 1px solid #cbd5e1; vertical-align: top; }
    .badge { display: inline-block; padding: 2px 6px; font-size: 9pt; border-radius: 4px; background: #e0e7ff; color: #3730a3; }
    .footer { margin-top: 40pt; font-size: 9pt; color: #64748b; border-top: 1px solid #e2e8f0; padding-top: 8pt; }
  </style>
</head>
<body>
  <h1>${project.title}</h1>
  <p><strong>Document Type:</strong> Technical System Design Specification</p>
  <p><strong>Generated By:</strong> StackFlow AI</p>
  <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
  
  <h2>1. Project Summary & Key Highlights</h2>
  <p>${design.summary}</p>
  
  <h3>Key Features:</h3>
  <ul>
    ${(design.keyFeatures || []).map(f => `<li>${f}</li>`).join("")}
  </ul>

  <h2>2. Functional Modules</h2>
  ${(design.modules || []).map((m, idx) => `
    <h3>Module ${idx + 1}: ${m.name}</h3>
    <p>${m.description}</p>
    <p><strong>Core Responsibilities:</strong></p>
    <ul>
      ${(m.responsibilities || []).map(r => `<li>${r}</li>`).join("")}
    </ul>
  `).join("")}

  <h2>3. Database Schema Specification</h2>
  <p><strong>Database Engine:</strong> ${design.database?.databaseType || "Relational / PostgreSQL"}</p>
  ${(design.database?.tables || []).map(tbl => `
    <h3>Table: <code>${tbl.name}</code></h3>
    <p>${tbl.description}</p>
    <table>
      <thead>
        <tr>
          <th>Field Name</th>
          <th>Data Type</th>
          <th>Keys</th>
          <th>Nullable</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        ${(tbl.fields || []).map(f => `
          <tr>
            <td><strong>${f.name}</strong></td>
            <td><code>${f.type}</code></td>
            <td>${f.isPrimaryKey ? '<span class="badge">PRIMARY KEY</span> ' : ''}${f.isForeignKey ? `<span class="badge">FK &rarr; ${f.references || ''}</span>` : ''}</td>
            <td>${f.isNullable ? 'YES' : 'NO'}</td>
            <td>${f.description}</td>
          </tr>
        `).join("")}
      </tbody>
    </table>
  `).join("")}

  <h2>4. REST API Endpoint Specifications</h2>
  <table>
    <thead>
      <tr>
        <th>Method</th>
        <th>Endpoint</th>
        <th>Auth</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      ${(design.apis || []).map(api => `
        <tr>
          <td><strong>${api.method}</strong></td>
          <td><code>${api.endpoint}</code></td>
          <td>${api.authentication ? "Required" : "Public"}</td>
          <td>${api.description}</td>
        </tr>
      `).join("")}
    </tbody>
  </table>

  <h2>5. System Architecture & Component Flow</h2>
  <p><strong>Architecture Pattern:</strong> ${design.architecture?.pattern || "Distributed Microservices"}</p>
  <table>
    <thead>
      <tr>
        <th>Layer</th>
        <th>Component</th>
        <th>Technology</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      ${(design.architecture?.components || []).map(comp => `
        <tr>
          <td>${comp.layer}</td>
          <td><strong>${comp.name}</strong></td>
          <td><code>${comp.technology}</code></td>
          <td>${comp.description}</td>
        </tr>
      `).join("")}
    </tbody>
  </table>

  <h2>6. Technology Stack Justification</h2>
  <table>
    <thead>
      <tr>
        <th>Category</th>
        <th>Chosen Technology</th>
        <th>Architectural Justification</th>
      </tr>
    </thead>
    <tbody>
      ${(design.technologyStack || []).map(t => `
        <tr>
          <td><strong>${t.category}</strong></td>
          <td>${t.name}</td>
          <td>${t.reason}</td>
        </tr>
      `).join("")}
    </tbody>
  </table>

  <h2>7. Architectural & Operational Recommendations</h2>
  ${(design.recommendations || []).map(rec => `
    <p><strong>[${rec.category}] ${rec.title} (${rec.priority} Priority):</strong> ${rec.description}</p>
  `).join("")}

  <h2>8. Deployment & CI/CD Pipeline</h2>
  <table>
    <thead>
      <tr>
        <th>Stage</th>
        <th>Step</th>
        <th>Tool</th>
        <th>Details</th>
      </tr>
    </thead>
    <tbody>
      ${(design.deployment || []).map(d => `
        <tr>
          <td><strong>${d.stage}</strong></td>
          <td>${d.step}</td>
          <td><code>${d.tool}</code></td>
          <td>${d.details}</td>
        </tr>
      `).join("")}
    </tbody>
  </table>

  <div class="footer">
    <p>Generated automatically with StackFlow AI — Enterprise Architecture & System Design Engine.</p>
  </div>
</body>
</html>
  `;

  const blob = new Blob(["\ufeff" + content], {
    type: "application/msword;charset=utf-8"
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${(project.title || "system-design").toLowerCase().replace(/[^a-z0-9]+/g, "-")}-design.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

import { exportExecutivePDF } from "./executivePdfGenerator.js";
export { exportExecutivePDF };

export function exportProjectToPDF(project) {
  return exportExecutivePDF(project);
}

export function exportProjectToJSON(project) {
  if (!project) return;
  const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(project, null, 2));
  const downloadAnchor = document.createElement("a");
  downloadAnchor.setAttribute("href", dataStr);
  downloadAnchor.setAttribute("download", `${(project.title || "system-design").toLowerCase().replace(/[^a-z0-9]+/g, "-")}-architecture.json`);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
}

